version: "3.1"
web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7.2-fpm
    volumes:
        - ./code:/code


        services:

            memcached:
              image: memcached:alpine
              container_name: lo-memcached

            redis:
              image: redis:alpine
              container_name: lo-redis

            mysql:
              image: mysql:8.0
              container_name: lo-mysql
              working_dir: /application
              volumes:
                - .:/application
              environment:
                - MYSQL_ROOT_PASSWORD=root
                - MYSQL_DATABASE=Database
                - MYSQL_USER=mydatabase
                - MYSQL_PASSWORD=root
              ports:
                - "8082:3306"

            webserver:
              image: nginx:alpine
              container_name: lo-webserver
              working_dir: /application
              volumes:
                  - .:/application
                  - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
              ports:
               - "8080:80"

            php-fpm:
              build: phpdocker/php-fpm
              container_name: lo-php-fpm
              working_dir: /application
              volumes:
                - .:/application
                - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

